/* **************************************************************************************************************************
*  Author: Xingguo Zhang   
*  Date: 12/30/2016   
*  Description: Eddy created a excel file Q:\ForecastExt\Feb 17 Forecast\QC_Check\Vw_forlagexpmos_QC.xlsx, we use this file 
*               as the source data to dertermine if one cell is large cell or not. The file is imported into SAS in the 
*               work library with name sasuser.Sourcelarge.
* Note: Need to run Initialize_94_PC.sas to establish all those library in SAS

*****************************************************************************************************************************/

DM 'LOG' CLEAR;
libname VWCODE  'Q:\ForecastOFM\Production\NwCycle1912_01\home\Forecast Process Specific Files\ViewsCode';
libname MainDm  'Q:\ForecastOFM\Production\NwCycle1912_01\Data\MainDm';
/*%let x = %sysfunc(pathname(MainDm));*/
/*%put &x;*/


%let FY = 2018; /* we choose 2017 for 1905 cycle because the total dollars are way bigger  FY = 2017,2018*/
proc sql;

CREATE table Vw_AfrsSumLagExpMos_zxg AS 
SELECT DISTINCT a.Afrs_Cycle_ID, a.Afrs_Meg_ID, a.Afrs_Svc_ID, a.CalendarYearMonth_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
       sum(a.AfrsExpenditure*b.AfrsExpenditureLag) as AfrsExpenditure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
FROM (SELECT x.*, y.Afrs_Svc_ID, y.Afrs_Meg_ID, z.FundType_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      FROM MainDm.Fact_Afrs_Expenditure as x,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
           MainDm.Map_Afrs_Expenditure as y,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
           MainDm.Dim_Afrs_ExpAuthIndex as w,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
           MainDm.Dim_FundType as z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      WHERE x.Afrs_ExpenditureMapping_ID=y.Afrs_ExpenditureMapping_ID 
            AND y.Afrs_ExpAuthIndex_ID=w.Afrs_ExpAuthIndex_ID 
            AND w.FundType=z.FundType
      ) a,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 MainDm.Fact_Afrs_ExpenditureLag as b
 WHERE a.Afrs_Cycle_ID=b.Afrs_Cycle_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
       a.CalendarYearMonth_ID=b.CalendarYearMonth_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	   a.Afrs_Svc_ID=b.Afrs_Svc_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
GROUP BY a.Afrs_Cycle_ID, a.Afrs_Meg_ID, a.Afrs_Svc_ID, a.CalendarYearMonth_ID;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
QUIT;             





proc sql;
CREATE table Vw_ForLagExpMos_zxg AS
SELECT DISTINCT d.AfrsCycle, e.ForMeg, f.ForSvc,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
h.CalendarYearMonth as ServiceMonth, h.FiscalYear, sum(a.AfrsExpenditure) as ForExpenditure,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
e.For_Meg_ID, f.For_Svc_ID, h.CalendarYearMonth_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
FROM Vw_AfrsSumLagExpMos_zxg a,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
     (SELECT * FROM  VwCode.Vw_AfrsForMegMap) b,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	 (SELECT * FROM VwCode.Vw_AfrsForSvcMap) c,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
     MainDm.Dim_Afrs_Cycle d,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
	 MainDm.Dim_For_Meg e,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	 MainDm.Dim_For_Svc f,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	 MainDm.Dim_CalendarYearMonth h                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 	 WHERE a.Afrs_Meg_ID=b.Afrs_Meg_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		   a.Afrs_Svc_ID=c.Afrs_Svc_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		   b.For_Meg_ID=e.For_Meg_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		   c.For_Svc_ID=f.For_Svc_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
           a.Afrs_Cycle_ID=d.Afrs_Cycle_ID AND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		   a.CalendarYearMonth_ID=h.CalendarYearMonth_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
GROUP BY AfrsCycle, e.ForMeg, f.ForSvc, ServiceMonth                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ORDER BY AfrsCycle, ForMeg, ForSvc, ServiceMonth;      
quit;

data source;
  set Vw_ForLagExpMos_zxg;
  where FiscalYear in( &FY ) AND ForExpenditure>=0;
run; 

libname VWCODE clear;


/*proc sql;*/
/*  select distinct FiscalYear*/
/*  from Vw_ForLagExpMos_zxg;*/
/*quit;*/

data _null_;
  set source  end =eof;
  total+ForExpenditure;
  if eof then call symputx ('total',total);
run; 

%put +++++++++++++++++++++&total+++++;


proc sql;
 create table totalByCell as 
 select ForMeg, ForSvc,sum(ForExpenditure) as CellTotal
 from source
 group by ForMeg, ForSvc 
 order by CellTotal desc, ForMeg, ForSvc;
quit; 


data list   ;
    set totalByCell end =eof;
	total +CellTotal;
	output list;
    if (eof or total ge 0.95*input(&total,20.)) then stop;  
	/* if use input(&total,20.2), the converted numeric values has changed, becasue the decimial point taken some lenght in the orginal char 
       see the example below
	*/
	
run; 

proc print data = list;
run; 

/* example to show the input(&total,20.)

data new;
 x = '778112124';
 y = input(x,20.2);
 z= input(x,20.);
run; 

proc print data = new;
run; 

*/
