
/******************************************************************
* Purpose: to take in the business people's idea to modify the model
* Author: Xingguo Zhang
* Date: 12/14/2017
****************************************************************/
dm 'log' clear;
%let category = 1230;
%let service = 310;
%let cycle=1724;
title "R_&category._&service._newmodel_&cycle._1";



Data dataForPlot 	(rename=(Act=Actual STPriorPerCap=PriorPerCap_withSteps                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
							 PriorPerCap=PriorPerCap_noSteps Pred=CurrentPerCap)
                    );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	Set PmTrend.R_&category._&service._newmodel_&cycle._1; 
Run;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
%let timenow=%sysfunc(time(), time.);			*Set up timestamp;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
%let datenow=%sysfunc(date(), date9.);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Title1	h=1.75 C=DarkBlue "Per Capita Expenditure" ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
Title2	h=1.25 C=DarkBlue "Forecast";		/*(SC) &Forecast macro is assigned in Initialize_94*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
%let when = "01Jun2010"d;
%put when is +++++++++++++&when++++++++++++; 
ods pdf file =  "\\profiles.eclient.wa.lcl\ofmprofile$\xingguoZ\desktop\&category._&service._&cycle..pdf" style=SASWEB; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Proc Gplot data = dataForPlot(WHERE=(DATE >= &when));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		Options nodate;			
		Legend1 Label=(Height=1 Position=top justify=left 'Legend');			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
		axis1 label=(angle=90 "Per Cap Expenditure"); 			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
	  PLOT 	PriorPerCap_withSteps * date=8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
			PriorPerCap_noSteps * date=13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
			CurrentPerCap * date = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
			Actual * date = 1/Overlay                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
				             vaxis = axis1      								                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
				             cframe=&CframeColor1
							 CHREF=(blue)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
				             autovref cvref=pink							/*Set up reference horizontal lines, ZXG: change the color from pink to graycc  */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
				             autohref chref=pink							/*Set up reference vertical lines*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
				             Legend=Legend1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
				             skipmiss;                
				format 	 Actual PriorPerCap_withSteps PriorPerCap_noSteps CurrentPerCap                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
								PerCap PerCapDiff STPercapDiff Residual adjPerCap	dollar19.0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
   run;
  Quit; 

ods pdf close; 


proc print data = dataForPlot;
run; 

proc sql;
  update dataForPlot
    set CurrentPerCap= CurrentPerCap - 0.3
where date>="01Feb2017"d;
quit;

/*Plot the new graph to compare the change after the modification */
ods pdf file =  "\\profiles.eclient.wa.lcl\ofmprofile$\xingguoZ\desktop\up_dated_&category._&service._&cycle..pdf" style=SASWEB; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Proc Gplot data = dataForPlot(WHERE=(DATE >= &when));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		Options nodate;			
		Legend1 Label=(Height=1 Position=top justify=left 'Legend');			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
		axis1 label=(angle=90 "Per Cap Expenditure"); 			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
	  PLOT 	PriorPerCap_withSteps * date=8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
			PriorPerCap_noSteps * date=13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
			CurrentPerCap * date = 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
			Actual * date = 1/Overlay                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
				             vaxis = axis1      								                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
				             cframe=&CframeColor1
							 CHREF=(blue)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
				             autovref cvref=pink							/*Set up reference horizontal lines, ZXG: change the color from pink to graycc  */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
				             autohref chref=pink							/*Set up reference vertical lines*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
				             Legend=Legend1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
				             skipmiss;                
				format 	 Actual PriorPerCap_withSteps PriorPerCap_noSteps CurrentPerCap                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
								PerCap PerCapDiff STPercapDiff Residual adjPerCap	dollar19.0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
   run;
  Quit; 

ods pdf close; 
